### PR TITLE
Port PR #153 (add support for onboard orientation estimation) to ROS2

### PR DESCRIPTION
**Pull request by mintar**

### CODE REVIEW

**Comment by mintar** [comment]
Still work in progress. I don't have a MOT109, so I can't test this PR.

**Comment by mklpiening** [comment]
I just tested the pr on ros2 humble woth a MOT0109.
There is still a typo in the *phidgets_spatial* *spatial-launch.py*. After using the "params" dict for the node parameters instead of "do_params" in line 57, it works well and I get the internally estimated orientation when enabling the "use_orientation" option.

Thus, this PR can be merged from my side.

**Comment by mintar** [comment]
Thanks for testing! I've fixed up the code with your suggestion and merged the PR.

**Comment by samerhanoun** [comment]
Hi Martin, 
Tested your latest merged code (that you merged 5 days ago for both phidgets_spatial and phidgets_api) using a PhidgetSpatial Preceision 3/3/3 MOT0110_0 on ROS2 Humble. Launching using use_orientation: true via spatial-launch.py, the code fails to set the magnetometer gain. Please see attached phots.

Regards,
 Samer

launch spatial-launch py with 'use_orientation'_ True

**Comment by mintar** [comment]
I've just pushed a PR (#169) that should fix your problem. Please test and report back.

**Comment by samerhanoun** [comment]
Works now.

**Pull request merged**
