### PR TITLE
Existing phidget cleanup

### PR DESCRIPTION
**Pull request by clalancette**
This fairly large PR does a pretty comprehensive cleanup of the existing codebase without adding anything new.  In particular:

1.  It cleans up the style so it is consistent across the project.
1.  It moves and removes some dependencies around so they are in the correct locations.
1.  It removes boost from the project; it was lightly used, and removing boost will make an eventual ROS 2 port easier.
1.  It makes sure that all of the `CPhidget` API calls are at the phidgets_api layer.
1.  It implements a node and nodelet version of all the supported phidget devices.
1.  It splits the custom messages and services into a separate phidgets_msgs package.  This will be useful when adding new phidgets based on libphidget2.2.

The follow-on to this PR will introduce libphidget22, and implement some phidgets based on that library.  The follow-on to *that* will be a port to ROS 2.

@mintar This is a large PR, so I'd suggest reviewing commit-by-commit, since each commit is a self-contained logical unit.  Alternatively, let me know if you'd like me to split it up into smaller PRs that may be easier to review.

### CODE REVIEW

**Comment by jlblancoc** [comment]
Shouldn't this be the perfect chance to add .clangformat files to enforce a consistent formatting? :-)

**Comment by clalancette** [comment]
> Shouldn't this be the perfect chance to add .clangformat files to enforce a consistent formatting? :-)

I'm not personally a huge fan of `clang-format`; the fact that you can't specify the path to the format file with the command-line makes it awkward in basically all situations.  Nevertheless, if that's the way people want to go, I can add in some kind of support for it.

**Comment by mintar** [comment]
I'm going to review this after my vacation, but quickly: I agree that having any sort of automated formatting (clang, astyle, you name it) and a CI check that enforces it would be perfect.

**Comment by mintar** [comment]
Thanks a lot! I've just reviewed everything and tested it with a Phidgets IMU (since that's the only Phidgets device I have). Everything still works (as expected).

**Comment by clalancette** [comment]
> Thanks a lot! I've just reviewed everything and tested it with a Phidgets IMU (since that's the only Phidgets device I have). Everything still works (as expected).

Fantastic, thanks!  I'll presently open up another PR that switches to libphidgets22.

**Pull request merged**
