### PR TITLE
Add support for onboard orientation estimation and other new PhidgetSpatial features of MOT0109 and onwards

### PR DESCRIPTION
**Pull request by mklpiening**
This adds some new features of the new Spatial sensors. These include:
- onboard orientation estimation
- onboard orientation estimation algorithm
- onboard orientation estimation algorithm parameters
- control of heating element

### CODE REVIEW

**Comment by mintar** [comment]
Thanks a lot! I've tested this PR with my old Spatial 1044 to make sure this PR doesn't break anything, and it doesn't. Documentation is perfect as well.

**Comment by samerhanoun** [comment]
Hi mintar, any chance you can provide an expected timeline for having the phidget spatial onboard orientation estimation supported. Thanks.

**Comment by mintar** [comment]
I don't understand. It is already supported, that is exactly what this PR does.

**Comment by samerhanoun** [comment]
Dear Martin, thank you for your response. 

On ROS 2 Humble, using the Phidgets spatial ROS 2 driver with a PhidgetSpatial Precision 3/3/3 IMU, we are receiving zeros values for the orientation x, y, z; however, the robot is moving and changing heading. Please see attached image1.png for more details. 

I understand that for ROS Noetic there was a parameter use_orientation and the IMU Orientation Filter (imu_filter_madgwick) needed to be used; however, with ROS 2 Humble this was removed and assumed by default; however the orientation data as you can see attached.

Another issue we are seeing is while the robot is stationary the linear acceleration values are not zero. Please see attached image2.png.

Your help on this matter is much appreciated to understand what's going on with the IMU.


image 2


image 1

**Comment by mintar** [comment]
Ah, I see, you're using ROS2! This PR was not ported to ROS2 yet. I've created a PR that tries to do it: #168

I don't use ROS2 yet and don't have access to a MOT109 or better to test it. Can you test the PR and give feedback?

For your current problem: Without #168, there is no onboard orientation estimation, so you still have to use imu_filter_madgwick to get orientation data.

**Comment by samerhanoun** [comment]
Thanks Martin, for now the imu_filter_madgwick solves the issue to obtain the orientation data, tested your new edits, please see comment at https://github.com/ros-drivers/phidgets_drivers/pull/168

**Pull request merged**
