### PR TITLE
Update to libphidget22-1.7.20210816

### LINKED ISSUE #99: Anyway to get this pkg to work with PhidgetSpatial Precision 3/3/3 ID: MOT0109_0
Since all the old imus are discontinued is there any way to get this pkg to work with ROS

### LINKED ISSUE #105: MOT0109_0: Spatial: Failed to open device: Timed Out
did anyone encounter this before?
on branch noetic.
i have the phidgets spatial 3/3/3 MOT0109_0, i'm trying to launch the spatial.launch and i get these errors:

[ INFO] [1634714179.485430556]: Loading nodelet /PhidgetsSpatialNodelet of type phidgets_spatial/PhidgetsSpatialNodelet to manager imu_manager with the following remappings:
[ INFO] [1634714179.487040471]: waitForService: Service [/imu_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1634714179.492581832]: Loading nodelet /ImuFilterNodelet of type imu_filter_madgwick/ImuFilterNodelet to manager imu_manager with the following remappings:
[ INFO] [1634714179.494079519]: waitForService: Service [/imu_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1634714179.504203262]: Initializing nodelet with 8 worker threads.
[ INFO] [1634714179.508148068]: waitForService: Service [/imu_manager/load_nodelet] is now available.
[ INFO] [1634714179.510623053]: Initializing Phidgets SPATIAL Nodelet
[ INFO] [1634714179.510687100]: Starting Phidgets SPATIAL
[ INFO] [1634714179.510703508]: Opening spatial
[ INFO] [1634714179.513058698]: Connecting to Phidgets Spatial serial 373265, hub port 0 ...
[ INFO] [1634714179.515118447]: waitForService: Service [/imu_manager/load_nodelet] is now available.
[ERROR] [1634714180.514098019]: Spatial: Failed to open device: Timed Out
[FATAL] [1634714180.515002304]: Failed to load nodelet '/PhidgetsSpatialNodelet` of type `phidgets_spatial/PhidgetsSpatialNodelet` to manager `imu_manager'
[ INFO] [1634714180.525610450]: Initializing IMU Filter Nodelet
[ INFO] [1634714180.528075648]: Starting ImuFilter
[ INFO] [1634714180.539780216]: Using dt computed from message headers
[ INFO] [1634714180.539883555]: The gravity vector is kept in the IMU message.
[ INFO] [1634714180.560925486]: Imu filter gain set to 0.100000
[ INFO] [1634714180.560996819]: Gyro drift bias set to 0.000000
[ INFO] [1634714180.561031830]: Magnetometer bias values: 0.000000 0.000000 0.000000
[PhidgetsSpatialNodelet-3] process has died [pid 6039, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load phidgets_spatial/PhidgetsSpatialNodelet imu_manager __name:=PhidgetsSpatialNodelet __log:=/home/user/.ros/log/9edd08f0-3175-11ec-92fd-b05cdaa8ff51/PhidgetsSpatialNodelet-3.log].
log file: /home/user/.ros/log/9edd08f0-3175-11ec-92fd-b05cdaa8ff51/PhidgetsSpatialNodelet-3*.log
[ WARN] [1634714190.572501364]: Still waiting for data on topics /imu/data_raw and /imu/mag...

can anyone help please?

### PR DESCRIPTION
**Pull request by mintar**
This is required to support new devices such as the MOT0109.

Fixes #99, fixes #105.

### CODE REVIEW

**Comment by mintar** [comment]
There's still one warning left that I'm not sure how to fix:

```text
src/vint.c: In function 'scanVintDevices':
src/vint.c:345:8: warning: 'usbConn' may be used uninitialized in this function [-Wmaybe-uninitialized]
  345 |    if (PhidgetUSBGetDeviceDescriptor(usbConn, USB_DESC_TYPE_VINT_PORT_DESC, i, (uint8_t *)&vintPortDesc, &bufLen) != EPHIDGET_OK) {
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

But even with that warning I think it's good to update the library in order to support new devices.

@clalancette : Any thoughts?

**Comment by mintar** [comment]
#105 is confirmed to be fixed by this PR.

**Comment by mintar** [comment]
Buildfarm checks are failing because of the warning above, so I guess we need to fix this. @clalancette : Any ideas?

**Comment by clalancette** [comment]
> Buildfarm checks are failing because of the warning above, so I guess we need to fix this. @clalancette : Any ideas?

For other issues of this nature, I've gone ahead and patched the source libphidget22 library; that's part of what https://github.com/ros-drivers/phidgets_drivers/blob/noetic/libphidget22/patch/libphidgets22-1.6.20200417-fix-warnings.patch does.  I'd suggest adding another diff to that patch.

(as a side note, the way that I developed that patch is:

1. Download the libphidget....tar.gz file, and unpack it.
1. Make a copy of the unmodified sources.
1. Apply the current https://github.com/ros-drivers/phidgets_drivers/blob/noetic/libphidget22/patch/libphidgets22-1.6.20200417-fix-warnings.patch
1. Build locally.
1. Make changes to the code until you get a warning free build.
1. Run `diff -Nurp orig_dir new_dir`, and save off the resulting patch.
1. Copy that patch into place in the phidgets_drivers/libphidget22/patch directory
)

**Comment by mintar** [comment]
Thanks for the detailed instructions! But I already figured out that procedure by myself and already adapted the patch file to the new library version. I know *how* to patch, I don't know what to change in the code. Sorry for not making myself clear.

The warning is because the compiler thinks that in line 345, `usbConn` could be uninitialized. Actually, it can't, because it gets initialized on line 260 in a different `switch` statement; the only way for it to be uninitialized would be if the value of `device->deviceInfo.UDD->uid` changed between the two switch statements. We know that this can't happen, but perhaps the compiler doesn't know that. 

One solution would be to reorganize the code so that initialization + usage of the variable happens in the same `case` block, but I don't want to make large untested changes to the code just to get rid of one spurious warning.

**Comment by mintar** [comment]
Never mind, I figured out a solution! Ready for review now.

**Comment by clalancette** [comment]
> Thanks for the detailed instructions! But I already figured out that procedure by myself and already adapted the patch file to the new library version. I know _how_ to patch, I don't know what to change in the code. Sorry for not making myself clear.

Ah, sorry I misunderstood.  It looks like you figured it out anyway, so I'll take a look at the patch itself.

**Review by clalancette — APPROVED** [review]
Looks good to me!  We should also cross-port this to the ROS 2 branches, as they could use a similar update.

**Comment by mintar** [comment]
> Looks good to me! We should also cross-port this to the ROS 2 branches, as they could use a similar update.

I created the PRs: #107, #108.

**Pull request merged**
